# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-15 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('brand', models.TextField()),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('image', models.ImageField(null=True, upload_to='images')),
            ],
        ),
    ]
