# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20200119_2245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car_detail',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='car_detail',
            name='extra_price',
        ),
        migrations.RemoveField(
            model_name='car_detail',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='car_detail',
            name='image3',
        ),
    ]
