# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20200120_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_detail',
            name='name',
        ),
        migrations.AddField(
            model_name='car',
            name='body_type',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='colour',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='engine_size',
            field=models.IntegerField(default='3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='fuel_type',
            field=models.TextField(default='body'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
    ]
