# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20200120_1825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Car_detail',
            new_name='Car_image',
        ),
    ]
