# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-01-20 19:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20200120_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
